// lib/data.ts

export type CatalogItem = {
  id: string
  title: string
  type: "club" | "sport" | "event" | "competition"
  description: string
  imageAlt: string
  imageUrl: string
  leader: string
  leaderId: string
}

export const catalogItems: CatalogItem[] = [
  {
    id: "c1",
    title: "Robotics Club",
    type: "club",
    description: "Build and program robots.",
    imageAlt: "Robotics Club",
    imageUrl: "/robotics-club.jpg",
    leader: "A. Kumar",
    leaderId: "user-a", 
  },
  {
    id: "c2",
    title: "Literary Club",
    type: "club",
    description: "Creative writing and debates.",
    imageAlt: "Literary Club",
    imageUrl: "/literary-club.jpg",
    leader: "S. Rao",
    leaderId: "user-b",
  },
  {
    id: "s1",
    title: "Football",
    type: "sport",
    description: "Team training and matches.",
    imageAlt: "Football",
    imageUrl: "/football-sport.jpg",
    leader: "Coach Dev",
    leaderId: "user-c",
  },
  {
    id: "e1",
    title: "Science Fair",
    type: "event",
    description: "Showcase your innovations.",
    imageAlt: "Science Fair",
    imageUrl: "/science-fair.jpg",
    leader: "Faculty Team",
    leaderId: "user-a", 
  },
  {
    id: "cmp1",
    title: "Math Olympiad",
    type: "competition",
    description: "Compete with the best.",
    imageAlt: "Math Olympiad",
    imageUrl: "/placeholder-jhalf.png",
    leader: "Dept. Math",
    leaderId: "user-d",
  },
  {
    id: "s2",
    title: "Basketball",
    type: "sport",
    description: "Practice and tournaments.",
    imageAlt: "Basketball",
    imageUrl: "/basketball-action.png",
    leader: "Coach Priya",
    leaderId: "user-e",
  },
  {
    id: "c3",
    title: "Drama Club",
    type: "club",
    description: "Acting, script, and stage.",
    imageAlt: "Drama Club",
    imageUrl: "/drama-club.jpg",
    leader: "R. Menon",
    leaderId: "user-a", 
  },
  {
    id: "e2",
    title: "Cultural Fest",
    type: "event",
    description: "Music, dance, and food.",
    imageAlt: "Cultural Fest",
    imageUrl: "/cultural-fest.jpg",
    leader: "Student Council",
    leaderId: "user-f",
  },

  {
    id: "s3",
    title: "Volleyball Team",
    type: "sport",
    description: "Spike, set, and block with the college team.",
    imageAlt: "Volleyball",
    imageUrl: "/placeholder-sport-vball.png",
    leader: "Coach K.",
    leaderId: "user-g",
  },
  {
    id: "s4",
    title: "Cricket Club",
    type: "sport",
    description: "Practice bowling and batting for campus tournaments.",
    imageAlt: "Cricket",
    imageUrl: "/placeholder-sport-cricket.png",
    leader: "P. Sharma",
    leaderId: "user-h",
  },
  {
    id: "s5",
    title: "Kabaddi Squad",
    type: "sport",
    description: "Training in raids, defense, and breathing control.",
    imageAlt: "Kabaddi",
    imageUrl: "/placeholder-sport-kabaddi.png",
    leader: "J. Singh",
    leaderId: "user-a", 
  },
  {
    id: "c4",
    title: "Sketch & Paint Club",
    type: "club",
    description: "Explore sketching, watercolor, and digital art techniques.",
    imageAlt: "Drawing Club",
    imageUrl: "/placeholder-club-art.png",
    leader: "M. Khanna",
    leaderId: "user-i",
  },
  {
    id: "s6",
    title: "Track & Field Athletics",
    type: "sport",
    description: "Focus on running, jumping, and throwing events.",
    imageAlt: "Athletics",
    imageUrl: "/placeholder-sport-track.png",
    leader: "Coach Dev",
    leaderId: "user-c",
  },
  {
    id: "c5",
    title: "Singing & Music Club",
    type: "club",
    description: "Vocal training, jam sessions, and public performances.",
    imageAlt: "Singing Club",
    imageUrl: "/placeholder-club-music.png",
    leader: "A. Reddy",
    leaderId: "user-j",
  },
  {
    id: "c6",
    title: "Chess Masters",
    type: "club",
    description: "Study openings, middle game tactics, and endgame theory.",
    imageAlt: "Chess Club",
    imageUrl: "/placeholder-club-chess.png",
    leader: "V. Iyer",
    leaderId: "user-a", 
  },
  {
    id: "c7",
    title: "Carrom & Board Games",
    type: "club",
    description: "Casual meets for carrom, scrabble, and other board games.",
    imageAlt: "Carrom Club",
    imageUrl: "/placeholder-club-carrom.png",
    leader: "F. Khan",
    leaderId: "user-k",
  },
];